version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: payment-analytics-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: payments
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api:
    build:
      context: .
      dockerfile: api/dockerfile
    container_name: payment-analytics-api
    restart: unless-stopped
    env_file:
      - api.env
    ports:
      - "3333:3333"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - payment-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3333/api/simulator/status', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

  web:
    build:
      context: .
      dockerfile: web/dockerfile
    container_name: payment-analytics-web
    restart: unless-stopped
    env_file:
      - web.env
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - payment-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  payment-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local